### ISSUE TITLE
Submit Payment button not working

### ISSUE THREAD

**Issue by PetrMoodle** [dualcube/moodle-enrol_stripepayment#42] opened 2020-08-06 23:48 UTC
Hi DualCube Team, I am trying to test a transaction using this Stripe plugin but for some reason when I click on the Submit Payment button on the course page nothing happens. I believe I am following the install instructions step by step for the Moodle side and also for the Stripe account side so I am not sure what I am missing. I have tried with both a test API and live API codes, I have changed themes to avoid conflicts, and several other settings. What is strange is that the coupon feature is working correctly but clicking Submit Payment does not, the page doesn't even refresh or trigger an error as if the button is disabled.

Could you please let me know what I should try to troubleshoot the issue. I am using Moodle 3.7.

**Comment by muzetik** [comment] 2020-08-09 13:25
Hi, same thing here, nothing happens when Submit payment is clicked since latest version (06/08/2020) with latest moodle (git).

**Comment by muzetik** [comment] 2020-08-09 23:12
> Hi, same thing here, nothing happens when Submit payment is clicked since latest version (06/08/2020) with latest moodle (git).

latest update on postal code check is the cause, I reverted this modification and the Submit payment button is working again.

**Comment by trideepdm** [comment] 2020-08-10 00:38
Dear user, 
postal code is now a mandatory field for Stripe Payment. So, make sure you have to give a postal code for every transaction. Once you give valid card details with postal code then only the Submit payment button is working.

**Comment by PetrMoodle** [comment] 2020-08-10 02:04
> 
> 
> Dear user,
> postal code is now a mandatory field for Stripe Payment. So, make sure you have to give a postal code for every transaction. Once you give valid card details with postal code then only the Submit payment button is working.

Hi trideepdm, I cannot see a post code field in the payment screen (see screenshot attached), just a the card number, date and cvc. Or do you mean a post code needs to be added in the Stripe account not in Moodle?

![image](https://user-images.githubusercontent.com/69329665/89747289-7bff4a80-db01-11ea-9c47-4cd3b6992d27.png)

**Comment by trideepdm** [comment] 2020-08-10 04:55
Dear PetrMoodle,

Once you start filling your card details then the postal code field is automatically created at the last field as ZIP. Please have a look at the attachment. 

Thank you.
![Screenshot from 2020-08-10 10-19-59](https://user-images.githubusercontent.com/58814409/89752884-b9f57200-daf3-11ea-85c1-7ee8fb07c2c4.png)

**Comment by PetrMoodle** [comment] 2020-08-10 06:19
Hi trideepdm, no that isn't appearing unfortunately, please see screenshot. Even if I try using a real card number and details it still doesn't show.

![image](https://user-images.githubusercontent.com/69329665/89756230-3bb1c380-db25-11ea-85aa-1935f1b31bba.png)

**Comment by trideepdm** [comment] 2020-08-10 09:21
Dear PetrMoodle,

As I can see on your screenshot that is not valid card detail that's the reason the postal code isn't appearing. Please use valid card details then only the postal code is appearing. You can also look at my previous screenshot as that has valid card details so the postal code is showing also the font color was black where your invalid card details in red. Hope you understand the differences. For further details about valid test card details please have a look [https://stripe.com/docs/testing](url)

**Comment by muzetik** [comment] 2020-08-10 09:56
Hi, zip code does not show even with valid card. Le 10 août 2020 10:21, trideepdm <notifications@github.com> a écrit :
Dear PetrMoodle,
As I can see on your screenshot that is not valid card detail that's the reason the postal code isn't appearing. Please use valid card details then only the postal code is appearing. You can also look at my previous screenshot as that has valid card details so the postal code is showing also the font color was black where your invalid card details in red. Hope you understand the differences. For further details about valid test card details please have a look https://stripe.com/docs/testing

**Comment by PetrMoodle** [comment] 2020-08-10 23:34
Hi trideepdm, as I said and as muzitek also mentioned, even when I used valid card details the zip code still isn't showing.

**Comment by elisoulsafe** [comment] 2020-08-11 02:06
The ZIP field only appears when using USA credit card numbers, when you use credit card numbers from any other location the ZIP field does not appear making it impossible to proceed with payments from cards outside of USA.

You can confirm this by using any of these basic test numbers:
 https://stripe.com/docs/testing
Try using any of these numbers: https://stripe.com/docs/testing#cards
Then try Europe or Asia-Pacific cards here: https://stripe.com/docs/testing#international-cards

As you can see the ZIP field only appears when USA cards are entered. The issue is (a very stupid) IF statement inside the enrol.php file under /enrol/stripepayment:
Lines 171 to 177

      if ((typeof(postal) != "undefined" && postal !== null && postal.length > 0)) {
        if (event.error) {
          status = 0;
        } else {
          status = 1;
        }
      }

This if statement will always run, and because the ZIP field only appears when using USA cards, then all other cards will make this if statement set status to 0.

**Comment by albertopampin** [comment] 2020-08-18 06:38
Duplicate of #

> 
> ## _Edit/added_ = The issue I describe below has now been fixed.
> 
> The ZIP field only appears when using USA credit card numbers, when you use credit card numbers from any other location the ZIP field does not appear making it impossible to proceed with payments from cards outside of USA.
> 
> You can confirm this by using any of these basic test numbers:
> https://stripe.com/docs/testing
> Try using any of these numbers: https://stripe.com/docs/testing#cards
> Then try Europe or Asia-Pacific cards here: https://stripe.com/docs/testing#international-cards
> 
> As you can see the ZIP field only appears when USA cards are entered. The issue is (a very stupid) IF statement inside the enrol.php file under /enrol/stripepayment:
> Lines 171 to 177
> 
> ```
>   if ((typeof(postal) != "undefined" && postal !== null && postal.length > 0)) {
>     if (event.error) {
>       status = 0;
>     } else {
>       status = 1;
>     }
>   }
> ```
> 
> This if statement will always run, and because the ZIP field only appears when using USA cards, then all other cards will make this if statement set status to 0.

what is the best solution for this case? I change the zip code to var zip = '99501'; I am from Spain. Thank you

**Comment by elisoulsafe** [comment] 2020-08-20 04:51
> my original post...
> 
> what is the best solution for this case? I change the zip code to var
> 
> var status = 1;
> var postal = '99501';
> Is this Ok? I am from Spain. Thank you

This should be fixed with the new update from dualcupe .. at least it is for me.
You could simply comment out that if statement and hard code the status to be 1 :P but I recommend just updating the plugin..

**Closed** 2020-10-14 15:15 UTC
